### ISSUE TITLE
ProtonMail bridge - Unable to get folder list for

### ISSUE THREAD

**Issue by kacperpaluch** [joeyates/imap-backup#141]
Hello,

I set up imap-backup with ProtonMail Bridge. Here is my config:
```
{
  "version": "2.0",
  "accounts": [
    {
      "username": "MyUsername",
      "password": "MyPassword",
      "local_path": "/root/.imap-backup/my_backup_path",
      "folders": [

      ],
      "mirror_mode": true,
      "server": "127.0.0.1",
      "connection_options": {
        "ssl": false,
        "port": 1143
      }
    }
  ]
}
```

When I try to backup using imap backup I have an error:

```
I, [2022-12-25T00:19:46.000890 #315450]  INFO -- : Running backup of account: AccountName
I, [2022-12-25T00:19:46.095084 #315450]  INFO -- : Unable to get folder list for account AccountName
Traceback (most recent call last):
	18: from /usr/local/bin/imap-backup:23:in `<main>'
	17: from /usr/local/bin/imap-backup:23:in `load'
	16: from /var/lib/gems/2.7.0/gems/imap-backup-8.0.2/bin/imap-backup:11:in `<top (required)>'
	15: from /var/lib/gems/2.7.0/gems/imap-backup-8.0.2/lib/imap/backup/logger.rb:34:in `sanitize_stderr'
	14: from /var/lib/gems/2.7.0/gems/imap-backup-8.0.2/bin/imap-backup:12:in `block in <top (required)>'
	13: from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	12: from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	11: from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	10: from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	 9: from /var/lib/gems/2.7.0/gems/imap-backup-8.0.2/lib/imap/backup/cli.rb:58:in `backup'
	 8: from /var/lib/gems/2.7.0/gems/imap-backup-8.0.2/lib/imap/backup/cli/backup.rb:16:in `run'
	 7: from /var/lib/gems/2.7.0/gems/imap-backup-8.0.2/lib/imap/backup/cli/helpers.rb:88:in `each_connection'
	 6: from /var/lib/gems/2.7.0/gems/imap-backup-8.0.2/lib/imap/backup/cli/helpers.rb:88:in `each'
	 5: from /var/lib/gems/2.7.0/gems/imap-backup-8.0.2/lib/imap/backup/cli/helpers.rb:91:in `block in each_connection'
	 4: from /var/lib/gems/2.7.0/gems/imap-backup-8.0.2/lib/imap/backup/cli/backup.rb:17:in `block in run'
	 3: from /var/lib/gems/2.7.0/gems/imap-backup-8.0.2/lib/imap/backup/account/connection.rb:41:in `run_backup'
	 2: from /var/lib/gems/2.7.0/gems/imap-backup-8.0.2/lib/imap/backup/account/connection.rb:27:in `backup_folders'
	 1: from /var/lib/gems/2.7.0/gems/imap-backup-8.0.2/lib/imap/backup/account/connection/backup_folders.rb:15:in `run'
/var/lib/gems/2.7.0/gems/imap-backup-8.0.2/lib/imap/backup/account/connection/folder_names.rb:20:in `run': Unable to get folder list for account AccountName (RuntimeError)
```

Any idea how to fix it?

**Comment by joeyates** [comment]
Hi @kacperpaluch 

Thanks for reporting this issue.

I have a couple of questions:

Could you please try to connect imap-backup to Proton Mail directly, without going through Proton Mail Bridge? Do you get the same error?

Secondly, how many folders are present on your account?

**Comment by kacperpaluch** [comment]
@joeyates
1. About 32 folders
2. Proton Mail doesn't have imap/smtp support so I can connect just using ProtonMail Bridge. 
3. I've tried to download all data using https://github.com/rcarmo/imapbackup and also I've synced ProtonMail (via Bridge) to another server using imapsync and everything works fine.

**Comment by joeyates** [comment]
@kacperpaluch OK, sounds like you've got a working solution. Let's keep this issue open so I can track resolving it with imap-backup.

**Comment by yi-ge** [comment]
I have the same problem

**Comment by kacperpaluch** [comment]
imap-backup with newest version of Proton Bridge works fine
