### ISSUE TITLE
uninitialized constant Imap (NameError)

### ISSUE THREAD

**Issue by MatejKovacic** [joeyates/imap-backup#162]
I updated `imap-backup` to the latest version by running: `gem install imap-backup`:
```

Fetching imap-backup-10.0.0.gem
Successfully installed imap-backup-10.0.0
Parsing documentation for imap-backup-10.0.0
Installing ri documentation for imap-backup-10.0.0
Done installing documentation for imap-backup after 0 seconds
1 gem installed
```

But when I run it, I get:

```
/home/matej/gems/gems/imap-backup-10.0.0/lib/imap/backup/client/default.rb:4:in `<top (required)>': uninitialized constant Imap (NameError)

module Imap::Backup
       ^^^^
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/matej/gems/gems/imap-backup-10.0.0/lib/imap/backup/client/apple_mail.rb:1:in `<top (required)>'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/matej/gems/gems/imap-backup-10.0.0/lib/imap/backup/account/client_factory.rb:4:in `<top (required)>'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/matej/gems/gems/imap-backup-10.0.0/lib/imap/backup/account.rb:1:in `<top (required)>'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/matej/gems/gems/imap-backup-10.0.0/lib/imap/backup/configuration.rb:5:in `<top (required)>'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/matej/gems/gems/imap-backup-10.0.0/lib/imap/backup/logger.rb:4:in `<top (required)>'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/matej/gems/gems/imap-backup-10.0.0/lib/imap/backup/cli.rb:2:in `<top (required)>'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /home/matej/gems/gems/imap-backup-10.0.0/bin/imap-backup:8:in `<top (required)>'
	from /home/matej/gems/bin/imap-backup:25:in `load'
	from /home/matej/gems/bin/imap-backup:25:in `<main>'
```
Any idea what is the problem?

**Comment by joeyates** [comment]
Hi @MatejKovacic 

Thanks for opening the issue.

I'm preparing a fix. In the meantime, could you let me know exactly what command you ran?

**Comment by MatejKovacic** [comment]
`imap-backup`, `imap-backup -v` and `imap-backup setup`

**Comment by MatejKovacic** [comment]
(actually, it has already been setup)

**Comment by joeyates** [comment]
It remains a mystery why it was happening, I haven't been able to reproduce.

But, I've released version 10.0.1, which should resolve it anyway!

**Comment by MatejKovacic** [comment]
It works! Thanks.

**Comment by chenrui333** [comment]
if helpful, this is the homebrew build of 10.0.0 release, https://github.com/Homebrew/homebrew-core/actions/runs/5568635707/jobs/10174629308

([10.0.1](https://github.com/Homebrew/homebrew-core/pull/136748) works for me)
