### ISSUE TITLE
Incompatible character encodings: UTF-8 and ASCII-8BIT

### ISSUE THREAD

**Issue by MatejKovacic** [joeyates/imap-backup#166]
I am getting this error:
```
E, [2023-08-07T10:11:51.078937 #328175] ERROR -- : Imap::Backup::Account::Backup error incompatible character encodings: UTF-8 and ASCII-8BIT
/home/matej/gems/gems/imap-backup-11.0.1/lib/email/mboxrd/message.rb:31:in `+'
/home/matej/gems/gems/imap-backup-11.0.1/lib/email/mboxrd/message.rb:31:in `to_serialized'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/serializer/delayed_metadata_serializer.rb:35:in `append'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/downloader.rb:95:in `handle_uid_and_body'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/downloader.rb:78:in `block in download_block'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/downloader.rb:77:in `each'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/downloader.rb:77:in `with_index'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/downloader.rb:77:in `download_block'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/downloader.rb:32:in `block in run'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/downloader.rb:31:in `each'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/downloader.rb:31:in `each_slice'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/downloader.rb:31:in `with_index'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/downloader.rb:31:in `run'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/account/backup.rb:76:in `block in backup_folder'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/serializer/delayed_metadata_serializer.rb:25:in `block (2 levels) in transaction'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/serializer/mbox.rb:19:in `block in transaction'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/serializer/transaction.rb:17:in `begin'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/serializer/mbox.rb:18:in `transaction'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/serializer/delayed_metadata_serializer.rb:24:in `block in transaction'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/serializer/transaction.rb:17:in `begin'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/serializer/delayed_metadata_serializer.rb:23:in `transaction'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/account/backup.rb:75:in `backup_folder'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/account/backup.rb:38:in `block in run'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/account/backup_folders.rb:39:in `block in each'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/account/backup_folders.rb:39:in `each'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/account/backup_folders.rb:39:in `each'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/account/backup.rb:37:in `run'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/cli/backup.rb:29:in `block in run'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/cli/backup.rb:27:in `each'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/cli/backup.rb:27:in `run'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/cli.rb:72:in `backup'
/home/matej/gems/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
/home/matej/gems/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
/home/matej/gems/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
/home/matej/gems/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/cli.rb:45:in `start'
/home/matej/gems/gems/imap-backup-11.0.1/bin/imap-backup:12:in `block in <top (required)>'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/logger.rb:41:in `sanitize_stderr'
/home/matej/gems/gems/imap-backup-11.0.1/bin/imap-backup:11:in `<top (required)>'
/home/matej/gems/bin/imap-backup:25:in `load'
/home/matej/gems/bin/imap-backup:25:in `<main>'

E, [2023-08-07T10:11:51.079056 #328175] ERROR -- : Imap::Backup::Serializer::Mbox error incompatible character encodings: UTF-8 and ASCII-8BIT
/home/matej/gems/gems/imap-backup-11.0.1/lib/email/mboxrd/message.rb:31:in `+'
/home/matej/gems/gems/imap-backup-11.0.1/lib/email/mboxrd/message.rb:31:in `to_serialized'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/serializer/delayed_metadata_serializer.rb:35:in `append'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/downloader.rb:95:in `handle_uid_and_body'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/downloader.rb:78:in `block in download_block'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/downloader.rb:77:in `each'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/downloader.rb:77:in `with_index'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/downloader.rb:77:in `download_block'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/downloader.rb:32:in `block in run'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/downloader.rb:31:in `each'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/downloader.rb:31:in `each_slice'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/downloader.rb:31:in `with_index'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/downloader.rb:31:in `run'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/account/backup.rb:76:in `block in backup_folder'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/serializer/delayed_metadata_serializer.rb:25:in `block (2 levels) in transaction'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/serializer/mbox.rb:19:in `block in transaction'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/serializer/transaction.rb:17:in `begin'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/serializer/mbox.rb:18:in `transaction'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/serializer/delayed_metadata_serializer.rb:24:in `block in transaction'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/serializer/transaction.rb:17:in `begin'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/serializer/delayed_metadata_serializer.rb:23:in `transaction'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/account/backup.rb:75:in `backup_folder'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/account/backup.rb:38:in `block in run'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/account/backup_folders.rb:39:in `block in each'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/account/backup_folders.rb:39:in `each'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/account/backup_folders.rb:39:in `each'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/account/backup.rb:37:in `run'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/cli/backup.rb:29:in `block in run'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/cli/backup.rb:27:in `each'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/cli/backup.rb:27:in `run'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/cli.rb:72:in `backup'
/home/matej/gems/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
/home/matej/gems/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
/home/matej/gems/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
/home/matej/gems/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/cli.rb:45:in `start'
/home/matej/gems/gems/imap-backup-11.0.1/bin/imap-backup:12:in `block in <top (required)>'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/logger.rb:41:in `sanitize_stderr'
/home/matej/gems/gems/imap-backup-11.0.1/bin/imap-backup:11:in `<top (required)>'
/home/matej/gems/bin/imap-backup:25:in `load'
/home/matej/gems/bin/imap-backup:25:in `<main>'

E, [2023-08-07T10:11:51.079625 #328175] ERROR -- : Backup for account '***@***' failed with error incompatible character encodings: UTF-8 and ASCII-8BIT
/home/matej/gems/gems/imap-backup-11.0.1/lib/email/mboxrd/message.rb:31:in `+'
/home/matej/gems/gems/imap-backup-11.0.1/lib/email/mboxrd/message.rb:31:in `to_serialized'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/serializer/delayed_metadata_serializer.rb:35:in `append'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/downloader.rb:95:in `handle_uid_and_body'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/downloader.rb:78:in `block in download_block'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/downloader.rb:77:in `each'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/downloader.rb:77:in `with_index'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/downloader.rb:77:in `download_block'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/downloader.rb:32:in `block in run'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/downloader.rb:31:in `each'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/downloader.rb:31:in `each_slice'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/downloader.rb:31:in `with_index'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/downloader.rb:31:in `run'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/account/backup.rb:76:in `block in backup_folder'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/serializer/delayed_metadata_serializer.rb:25:in `block (2 levels) in transaction'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/serializer/mbox.rb:19:in `block in transaction'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/serializer/transaction.rb:17:in `begin'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/serializer/mbox.rb:18:in `transaction'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/serializer/delayed_metadata_serializer.rb:24:in `block in transaction'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/serializer/transaction.rb:17:in `begin'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/serializer/delayed_metadata_serializer.rb:23:in `transaction'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/account/backup.rb:75:in `backup_folder'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/account/backup.rb:38:in `block in run'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/account/backup_folders.rb:39:in `block in each'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/account/backup_folders.rb:39:in `each'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/account/backup_folders.rb:39:in `each'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/account/backup.rb:37:in `run'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/cli/backup.rb:29:in `block in run'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/cli/backup.rb:27:in `each'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/cli/backup.rb:27:in `run'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/cli.rb:72:in `backup'
/home/matej/gems/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
/home/matej/gems/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
/home/matej/gems/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
/home/matej/gems/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/cli.rb:45:in `start'
/home/matej/gems/gems/imap-backup-11.0.1/bin/imap-backup:12:in `block in <top (required)>'
/home/matej/gems/gems/imap-backup-11.0.1/lib/imap/backup/logger.rb:41:in `sanitize_stderr'
/home/matej/gems/gems/imap-backup-11.0.1/bin/imap-backup:11:in `<top (required)>'
/home/matej/gems/bin/imap-backup:25:in `load'
/home/matej/gems/bin/imap-backup:25:in `<main>'
```

**Comment by MatejKovacic** [comment]
Also, I forgot to mention I have `imap-backup-11.0.1` installed.

**Comment by joeyates** [comment]
Hi @MatejKovacic 

Thanks for the info. I'm going to close this issue in favour of #156 so all the info is kept together. Please check out [the candidate release indicated there](https://github.com/joeyates/imap-backup/issues/156#issuecomment-1675797670).
