### ISSUE TITLE
Backup command exits

### ISSUE THREAD

**Issue by puzzle9** [joeyates/imap-backup#217]
I use `alpine`
I need a backup, I'm not sure where the problem is

```
ruby 3.3.6 (2024-11-05 revision 75015d4c1f) [x86_64-linux-musl]
imap-backup 15.0.2
```

`config.json`
```
{
  "version": "2.2",
  "accounts": [
    {
      "username": "email@126.com",
      "password": "password",
      "local_path": "/root/.imap-backup/email.com",
      "folders": [
        "INBOX",
        "草稿箱",
        "已发送",
        "已删除",
        "垃圾邮件",
        "hello github",
        "ruanyf weekly"
      ],
      "server": "imap.126.com",
      "multi_fetch_size": 1,
      "reset_seen_flags_after_fetch": true
    }
  ],
  "download_strategy": "delay_metadata"
}
```

```
imap-backup backup -vv
I, [2024-11-15T14:24:49.544764 #1114]  INFO -- : Running backup of account: email@126.com
D, [2024-11-15T14:24:49.544858 #1114] DEBUG -- : Creating IMAP instance: imap.126.com, options: {:port=>993, :ssl=>{:min_version=>771}}
D, [2024-11-15T14:24:49.544929 #1114] DEBUG -- : Logging in: email@126.com/xxxxxxxxxxxxxxxx
S: * OK Coremail System IMap Server Ready(126com[6c62234a7721d45811debf430915950d])
C: RUBY0001 CAPABILITY
S: * CAPABILITY IMAP4rev1 XLIST SPECIAL-USE ID LITERAL+ STARTTLS APPENDLIMIT=71680000 XAPPLEPUSHSERVICE UIDPLUS X-CM-EXT-1 SASL-IR AUTH=XOAUTH2
S: RUBY0001 OK CAPABILITY completed
C: RUBY0002 LOGIN email@126.com [PASSWORD REDACTED]
S: RUBY0002 OK LOGIN completed
D, [2024-11-15T14:24:49.831385 #1114] DEBUG -- : Login complete
C: RUBY0003 LIST "" ""
S: * LIST (\Noselect) "/" ""
S: RUBY0003 OK LIST Completed
C: RUBY0004 LIST "" "*"
S: * LIST () "/" "INBOX"
S: * LIST (\Drafts) "/" "&g0l6P3ux-"
S: * LIST (\Sent) "/" "&XfJT0ZAB-"
S: * LIST (\Trash) "/" "&XfJSIJZk-"
S: * LIST (\Junk) "/" "&V4NXPpCuTvY-"
S: * LIST () "/" "&dcVr0pCuTvY-"
S: * LIST () "/" "hello github"
S: * LIST () "/" "ruanyf weekly"
S: RUBY0004 OK LIST Completed
C: RUBY0005 LIST "" "*"
S: * LIST () "/" "INBOX"
S: * LIST (\Drafts) "/" "&g0l6P3ux-"
S: * LIST (\Sent) "/" "&XfJT0ZAB-"
S: * LIST (\Trash) "/" "&XfJSIJZk-"
S: * LIST (\Junk) "/" "&V4NXPpCuTvY-"
S: * LIST () "/" "&dcVr0pCuTvY-"
S: * LIST () "/" "hello github"
S: * LIST () "/" "ruanyf weekly"
S: RUBY0005 OK LIST Completed
```

**Comment by joeyates** [comment]
Hi @puzzle9 

It's odd that it stops so abruptly.

I've released version `15.0.3.rc1` which has a lot more debug logging.

Please install it like this:

```sh
gem install imap-backup --no-doc --version 15.0.3.rc1
```

...and let me know if the logging gives more info about what is happening.

**Comment by puzzle9** [comment]
@joeyates 

```
D, [2024-11-16T11:48:54.473778 #748] DEBUG -- : Loading configuration
D, [2024-11-16T11:48:54.473940 #748] DEBUG -- : Starting backup of 1 accounts
I, [2024-11-16T11:48:54.473995 #748]  INFO -- : Running backup of account 'email@163.com'
D, [2024-11-16T11:48:54.474065 #748] DEBUG -- : Creating IMAP instance: imap.163.com, options: {:port=>993, :ssl=>{:min_version=>771}}
D, [2024-11-16T11:48:54.474134 #748] DEBUG -- : Logging in: email@163.com/xxxxxxxxxxxxxxxx
S: * OK Coremail System IMap Server Ready(163com[10774b260cc7a37d26d71b52404dcf5c])
C: RUBY0001 CAPABILITY
S: * CAPABILITY IMAP4rev1 XLIST SPECIAL-USE ID LITERAL+ STARTTLS APPENDLIMIT=71680000 XAPPLEPUSHSERVICE UIDPLUS X-CM-EXT-1 SASL-IR AUTH=XOAUTH2
S: RUBY0001 OK CAPABILITY completed
C: RUBY0002 LOGIN email@163.com [PASSWORD REDACTED]
S: RUBY0002 OK LOGIN completed
D, [2024-11-16T11:48:54.854494 #748] DEBUG -- : Login complete
D, [2024-11-16T11:48:54.855021 #748] DEBUG -- : Fetching provider root
C: RUBY0003 LIST "" ""
S: * LIST (\Noselect) "/" ""
S: RUBY0003 OK LIST Completed
D, [2024-11-16T11:48:54.930318 #748] DEBUG -- : Provider root is ''
D, [2024-11-16T11:48:54.930371 #748] DEBUG -- : Listing all account folders
C: RUBY0004 LIST "" "*"
S: * LIST () "/" "INBOX"
S: * LIST (\Drafts) "/" "&g0l6P3ux-"
S: * LIST (\Sent) "/" "&XfJT0ZAB-"
S: * LIST (\Trash) "/" "&XfJSIJZk-"
S: * LIST (\Junk) "/" "&V4NXPpCuTvY-"
S: * LIST () "/" "&dcVr0mWHTvZZOQ-"
S: RUBY0004 OK LIST Completed
D, [2024-11-16T11:48:55.003650 #748] DEBUG -- : Starting backup of 6 folders
D, [2024-11-16T11:48:55.003708 #748] DEBUG -- : Running backup for folder 'INBOX'
D, [2024-11-16T11:48:55.003756 #748] DEBUG -- : Checking whether folder 'INBOX' exists
C: RUBY0005 EXAMINE INBOX
S: RUBY0005 NO EXAMINE Unsafe Login. Please contact kefu@188.com for help
W, [2024-11-16T11:48:55.074606 #748]  WARN -- : Folder 'INBOX' does not exist on server
W, [2024-11-16T11:48:55.074684 #748]  WARN -- : /usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/folder.rb:185:in `examine'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/folder.rb:36:in `block in exist?'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/retry_on_error.rb:18:in `retry_on_error'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/folder.rb:35:in `exist?'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/folder_backup.rb:50:in `folder_ok?'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/folder_backup.rb:27:in `run'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/backup.rb:35:in `block in run'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/backup.rb:34:in `each'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/backup.rb:34:in `run'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/cli/backup.rb:38:in `block in run'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/cli/backup.rb:36:in `each'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/cli/backup.rb:36:in `run'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/cli.rb:94:in `backup'
/usr/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
/usr/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
/usr/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
/usr/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/base.rb:584:in `start'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/cli.rb:69:in `start'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/bin/imap-backup:16:in `block in <top (required)>'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/logger.rb:58:in `sanitize_stderr'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/bin/imap-backup:15:in `<top (required)>'
/usr/bin/imap-backup:25:in `load'
/usr/bin/imap-backup:25:in `<main>'
D, [2024-11-16T11:48:55.074730 #748] DEBUG -- : Folder 'INBOX' does not exist
I, [2024-11-16T11:48:55.074742 #748]  INFO -- : Skipping backup for folder 'INBOX' as it does not exist
D, [2024-11-16T11:48:55.074782 #748] DEBUG -- : Running backup for folder '草稿箱'
D, [2024-11-16T11:48:55.074825 #748] DEBUG -- : Checking whether folder '草稿箱' exists
C: RUBY0006 EXAMINE &g0l6P3ux-
S: RUBY0006 NO EXAMINE Unsafe Login. Please contact kefu@188.com for help
W, [2024-11-16T11:48:55.188388 #748]  WARN -- : Folder '草稿箱' does not exist on server
W, [2024-11-16T11:48:55.188465 #748]  WARN -- : /usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/folder.rb:185:in `examine'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/folder.rb:36:in `block in exist?'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/retry_on_error.rb:18:in `retry_on_error'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/folder.rb:35:in `exist?'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/folder_backup.rb:50:in `folder_ok?'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/folder_backup.rb:27:in `run'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/backup.rb:35:in `block in run'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/backup.rb:34:in `each'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/backup.rb:34:in `run'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/cli/backup.rb:38:in `block in run'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/cli/backup.rb:36:in `each'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/cli/backup.rb:36:in `run'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/cli.rb:94:in `backup'
/usr/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
/usr/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
/usr/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
/usr/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/base.rb:584:in `start'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/cli.rb:69:in `start'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/bin/imap-backup:16:in `block in <top (required)>'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/logger.rb:58:in `sanitize_stderr'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/bin/imap-backup:15:in `<top (required)>'
/usr/bin/imap-backup:25:in `load'
/usr/bin/imap-backup:25:in `<main>'
D, [2024-11-16T11:48:55.188528 #748] DEBUG -- : Folder '草稿箱' does not exist
I, [2024-11-16T11:48:55.188552 #748]  INFO -- : Skipping backup for folder '草稿箱' as it does not exist
D, [2024-11-16T11:48:55.188567 #748] DEBUG -- : Running backup for folder '已发送'
D, [2024-11-16T11:48:55.188575 #748] DEBUG -- : Checking whether folder '已发送' exists
C: RUBY0007 EXAMINE &XfJT0ZAB-
S: RUBY0007 NO EXAMINE Unsafe Login. Please contact kefu@188.com for help
W, [2024-11-16T11:48:55.263247 #748]  WARN -- : Folder '已发送' does not exist on server
W, [2024-11-16T11:48:55.263339 #748]  WARN -- : /usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/folder.rb:185:in `examine'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/folder.rb:36:in `block in exist?'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/retry_on_error.rb:18:in `retry_on_error'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/folder.rb:35:in `exist?'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/folder_backup.rb:50:in `folder_ok?'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/folder_backup.rb:27:in `run'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/backup.rb:35:in `block in run'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/backup.rb:34:in `each'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/backup.rb:34:in `run'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/cli/backup.rb:38:in `block in run'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/cli/backup.rb:36:in `each'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/cli/backup.rb:36:in `run'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/cli.rb:94:in `backup'
/usr/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
/usr/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
/usr/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
/usr/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/base.rb:584:in `start'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/cli.rb:69:in `start'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/bin/imap-backup:16:in `block in <top (required)>'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/logger.rb:58:in `sanitize_stderr'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/bin/imap-backup:15:in `<top (required)>'
/usr/bin/imap-backup:25:in `load'
/usr/bin/imap-backup:25:in `<main>'
D, [2024-11-16T11:48:55.263429 #748] DEBUG -- : Folder '已发送' does not exist
I, [2024-11-16T11:48:55.263479 #748]  INFO -- : Skipping backup for folder '已发送' as it does not exist
D, [2024-11-16T11:48:55.263508 #748] DEBUG -- : Running backup for folder '已删除'
D, [2024-11-16T11:48:55.263547 #748] DEBUG -- : Checking whether folder '已删除' exists
C: RUBY0008 EXAMINE &XfJSIJZk-
S: RUBY0008 NO EXAMINE Unsafe Login. Please contact kefu@188.com for help
W, [2024-11-16T11:48:55.335915 #748]  WARN -- : Folder '已删除' does not exist on server
W, [2024-11-16T11:48:55.335992 #748]  WARN -- : /usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/folder.rb:185:in `examine'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/folder.rb:36:in `block in exist?'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/retry_on_error.rb:18:in `retry_on_error'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/folder.rb:35:in `exist?'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/folder_backup.rb:50:in `folder_ok?'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/folder_backup.rb:27:in `run'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/backup.rb:35:in `block in run'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/backup.rb:34:in `each'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/backup.rb:34:in `run'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/cli/backup.rb:38:in `block in run'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/cli/backup.rb:36:in `each'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/cli/backup.rb:36:in `run'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/cli.rb:94:in `backup'
/usr/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
/usr/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
/usr/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
/usr/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/base.rb:584:in `start'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/cli.rb:69:in `start'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/bin/imap-backup:16:in `block in <top (required)>'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/logger.rb:58:in `sanitize_stderr'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/bin/imap-backup:15:in `<top (required)>'
/usr/bin/imap-backup:25:in `load'
/usr/bin/imap-backup:25:in `<main>'
D, [2024-11-16T11:48:55.336054 #748] DEBUG -- : Folder '已删除' does not exist
I, [2024-11-16T11:48:55.336096 #748]  INFO -- : Skipping backup for folder '已删除' as it does not exist
D, [2024-11-16T11:48:55.336147 #748] DEBUG -- : Running backup for folder '垃圾邮件'
D, [2024-11-16T11:48:55.336190 #748] DEBUG -- : Checking whether folder '垃圾邮件' exists
C: RUBY0009 EXAMINE &V4NXPpCuTvY-
S: RUBY0009 NO EXAMINE Unsafe Login. Please contact kefu@188.com for help
W, [2024-11-16T11:48:55.452066 #748]  WARN -- : Folder '垃圾邮件' does not exist on server
W, [2024-11-16T11:48:55.452138 #748]  WARN -- : /usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/folder.rb:185:in `examine'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/folder.rb:36:in `block in exist?'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/retry_on_error.rb:18:in `retry_on_error'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/folder.rb:35:in `exist?'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/folder_backup.rb:50:in `folder_ok?'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/folder_backup.rb:27:in `run'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/backup.rb:35:in `block in run'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/backup.rb:34:in `each'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/backup.rb:34:in `run'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/cli/backup.rb:38:in `block in run'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/cli/backup.rb:36:in `each'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/cli/backup.rb:36:in `run'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/cli.rb:94:in `backup'
/usr/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
/usr/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
/usr/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
/usr/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/base.rb:584:in `start'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/cli.rb:69:in `start'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/bin/imap-backup:16:in `block in <top (required)>'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/logger.rb:58:in `sanitize_stderr'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/bin/imap-backup:15:in `<top (required)>'
/usr/bin/imap-backup:25:in `load'
/usr/bin/imap-backup:25:in `<main>'
D, [2024-11-16T11:48:55.452201 #748] DEBUG -- : Folder '垃圾邮件' does not exist
I, [2024-11-16T11:48:55.452244 #748]  INFO -- : Skipping backup for folder '垃圾邮件' as it does not exist
D, [2024-11-16T11:48:55.452293 #748] DEBUG -- : Running backup for folder '病毒文件夹'
D, [2024-11-16T11:48:55.452335 #748] DEBUG -- : Checking whether folder '病毒文件夹' exists
C: RUBY0010 EXAMINE &dcVr0mWHTvZZOQ-
S: RUBY0010 NO EXAMINE Unsafe Login. Please contact kefu@188.com for help
W, [2024-11-16T11:48:55.524340 #748]  WARN -- : Folder '病毒文件夹' does not exist on server
W, [2024-11-16T11:48:55.524418 #748]  WARN -- : /usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/folder.rb:185:in `examine'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/folder.rb:36:in `block in exist?'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/retry_on_error.rb:18:in `retry_on_error'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/folder.rb:35:in `exist?'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/folder_backup.rb:50:in `folder_ok?'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/folder_backup.rb:27:in `run'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/backup.rb:35:in `block in run'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/backup.rb:34:in `each'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/account/backup.rb:34:in `run'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/cli/backup.rb:38:in `block in run'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/cli/backup.rb:36:in `each'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/cli/backup.rb:36:in `run'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/cli.rb:94:in `backup'
/usr/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
/usr/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
/usr/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
/usr/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/base.rb:584:in `start'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/cli.rb:69:in `start'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/bin/imap-backup:16:in `block in <top (required)>'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/lib/imap/backup/logger.rb:58:in `sanitize_stderr'
/usr/lib/ruby/gems/3.3.0/gems/imap-backup-15.0.3.rc1/bin/imap-backup:15:in `<top (required)>'
/usr/bin/imap-backup:25:in `load'
/usr/bin/imap-backup:25:in `<main>'
D, [2024-11-16T11:48:55.524459 #748] DEBUG -- : Folder '病毒文件夹' does not exist
I, [2024-11-16T11:48:55.524470 #748]  INFO -- : Skipping backup for folder '病毒文件夹' as it does not exist
D, [2024-11-16T11:48:55.524482 #748] DEBUG -- : Backup of account 'email@163.com' complete
D, [2024-11-16T11:48:55.524490 #748] DEBUG -- : Backup complete
```

Can you give me an email address
I will send you the account password

**Comment by joeyates** [comment]
From this section

```
C: RUBY0005 EXAMINE INBOX
S: RUBY0005 NO EXAMINE Unsafe Login. Please contact kefu@188.com for help
```

I'm guessing that there is some other authentication requirement to use IMAP properly with this server.

**Comment by puzzle9** [comment]
i use `outlook (classic)` is ok
