### ISSUE TITLE
Migrate crashes with not allowed character

### ISSUE THREAD

**Issue by btxtiger** [joeyates/imap-backup#223]
Hi,

I transferred some inboxes and one account had a custom folder `Person K.`.
When I used the `backup` command, the local created files were `Person K..imap` and `Person K..mbox`.
![image](https://github.com/user-attachments/assets/e33bed95-5884-471e-9d78-2e9c6bc71c0d)

When running `migrate` the script fails with this error:

```
/usr/lib/ruby/gems/3.2.0/gems/net-imap-0.3.4.1/lib/net/imap.rb:2170:in `get_tagged_response': Character not allowed in mailbox name: '.' (0.001 + 0.010 + 0.009 secs). (Net::IMAP::NoResponseError)
	from /usr/lib/ruby/gems/3.2.0/gems/net-imap-0.3.4.1/lib/net/imap.rb:2224:in `block in send_command'
	from /usr/lib/ruby/3.2.0/monitor.rb:202:in `synchronize'
	from /usr/lib/ruby/3.2.0/monitor.rb:202:in `mon_synchronize'
	from /usr/lib/ruby/gems/3.2.0/gems/net-imap-0.3.4.1/lib/net/imap.rb:2206:in `send_command'
	from /usr/lib/ruby/gems/3.2.0/gems/net-imap-0.3.4.1/lib/net/imap.rb:1130:in `create'
	from /usr/lib/ruby/3.2.0/forwardable.rb:240:in `create'
	from /var/lib/gems/3.2.0/gems/imap-backup-15.0.2/lib/imap/backup/client/automatic_login_wrapper.rb:28:in `method_missing'
	from /var/lib/gems/3.2.0/gems/imap-backup-15.0.2/lib/imap/backup/account/folder.rb:55:in `block in create'
	from /var/lib/gems/3.2.0/gems/imap-backup-15.0.2/lib/imap/backup/retry_on_error.rb:18:in `retry_on_error'
	from /var/lib/gems/3.2.0/gems/imap-backup-15.0.2/lib/imap/backup/account/folder.rb:54:in `create'
	from /var/lib/gems/3.2.0/gems/imap-backup-15.0.2/lib/imap/backup/migrator.rb:18:in `run'
	from /var/lib/gems/3.2.0/gems/imap-backup-15.0.2/lib/imap/backup/cli/transfer.rb:47:in `block in run'
	from /var/lib/gems/3.2.0/gems/imap-backup-15.0.2/lib/imap/backup/account/folder_mapper.rb:43:in `block in each'
	from <internal:dir>:220:in `glob'
	from /var/lib/gems/3.2.0/gems/imap-backup-15.0.2/lib/imap/backup/account/folder_mapper.rb:39:in `glob'
	from /var/lib/gems/3.2.0/gems/imap-backup-15.0.2/lib/imap/backup/account/folder_mapper.rb:39:in `each'
	from /var/lib/gems/3.2.0/gems/imap-backup-15.0.2/lib/imap/backup/cli/transfer.rb:44:in `run'
	from /var/lib/gems/3.2.0/gems/imap-backup-15.0.2/lib/imap/backup/cli.rb:156:in `migrate'
	from /var/lib/gems/3.2.0/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
	from /var/lib/gems/3.2.0/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /var/lib/gems/3.2.0/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
	from /var/lib/gems/3.2.0/gems/thor-1.3.2/lib/thor/base.rb:584:in `start'
	from /var/lib/gems/3.2.0/gems/imap-backup-15.0.2/lib/imap/backup/cli.rb:69:in `start'
	from /var/lib/gems/3.2.0/gems/imap-backup-15.0.2/bin/imap-backup:16:in `block in <top (required)>'
	from /var/lib/gems/3.2.0/gems/imap-backup-15.0.2/lib/imap/backup/logger.rb:58:in `sanitize_stderr'
	from /var/lib/gems/3.2.0/gems/imap-backup-15.0.2/bin/imap-backup:15:in `<top (required)>'
	from /usr/local/bin/imap-backup:25:in `load'
	from /usr/local/bin/imap-backup:25:in `<main>'
```

After removing one period, the migration worked properly (the restored folder was `Person K` then).

**Comment by joeyates** [comment]
Hi @jonaaix 

The use of `.` is blocked by the destination server , and depends on how it is configured.

As such, this is not a limitation imposed by imap-backup. It is also not error that can be trapped and ignored.
