### ISSUE TITLE
Setup crashes unless config file already exists

### ISSUE THREAD

**Issue by leth** [joeyates/imap-backup#25]
Gem version 1.0.15
```
$ imap-backup setup
~/.rvm/gems/ruby-1.9.3-p551@imap-backup/gems/imap-backup-1.0.15/lib/imap/backup/configuration/list.rb:30:in `config': Configuration file '~/.imap-backup/config.json' not found (Imap::Backup::ConfigurationNotFound)
	from ~/.rvm/gems/ruby-1.9.3-p551@imap-backup/gems/imap-backup-1.0.15/lib/imap/backup/configuration/list.rb:14:in `setup_logging'
	from ~/.rvm/gems/ruby-1.9.3-p551@imap-backup/gems/imap-backup-1.0.15/bin/imap-backup:60:in `<top (required)>'
	from ~/.rvm/gems/ruby-1.9.3-p551@imap-backup/bin/imap-backup:23:in `load'
	from ~/.rvm/gems/ruby-1.9.3-p551@imap-backup/bin/imap-backup:23:in `<main>'
	from ~/.rvm/gems/ruby-1.9.3-p551@imap-backup/bin/ruby_executable_hooks:15:in `eval'
	from ~/.rvm/gems/ruby-1.9.3-p551@imap-backup/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by joeyates** [comment]
Hello,

Thanks for the bug report.

I've released version 1.0.17 that fixes this.
