### ISSUE TITLE
Worked perfect... until some days ago... (get_tagged_response EOFError)

### ISSUE THREAD

**Issue by AntonTrapp** [joeyates/imap-backup#35]
Hi!

First: thank you for this great gem. Installed it, worked like a charm (with 1 bug, can live with that).

A few days ago it started to do this:

```
/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/imap.rb:1190:in `get_tagged_response': end of file reached (EOFError)
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/imap.rb:1250:in `block in send_command'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/imap.rb:1232:in `send_command'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/imap.rb:1401:in `block in fetch_internal'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/imap.rb:1399:in `fetch_internal'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/imap.rb:818:in `uid_fetch'
	from /usr/local/rvm/gems/ruby-2.3.0@imap-backup/gems/imap-backup-1.1.0/lib/imap/backup/account/folder.rb:36:in `fetch'
	from /usr/local/rvm/gems/ruby-2.3.0@imap-backup/gems/imap-backup-1.1.0/lib/imap/backup/downloader.rb:16:in `block in run'
	from /usr/local/rvm/gems/ruby-2.3.0@imap-backup/gems/imap-backup-1.1.0/lib/imap/backup/downloader.rb:15:in `each'
	from /usr/local/rvm/gems/ruby-2.3.0@imap-backup/gems/imap-backup-1.1.0/lib/imap/backup/downloader.rb:15:in `run'
	from /usr/local/rvm/gems/ruby-2.3.0@imap-backup/gems/imap-backup-1.1.0/lib/imap/backup/account/connection.rb:44:in `block in run_backup'
	from /usr/local/rvm/gems/ruby-2.3.0@imap-backup/gems/imap-backup-1.1.0/lib/imap/backup/account/connection.rb:69:in `block in each_folder'
	from /usr/local/rvm/gems/ruby-2.3.0@imap-backup/gems/imap-backup-1.1.0/lib/imap/backup/account/connection.rb:66:in `each'
	from /usr/local/rvm/gems/ruby-2.3.0@imap-backup/gems/imap-backup-1.1.0/lib/imap/backup/account/connection.rb:66:in `each_folder'
	from /usr/local/rvm/gems/ruby-2.3.0@imap-backup/gems/imap-backup-1.1.0/lib/imap/backup/account/connection.rb:42:in `run_backup'
	from /usr/local/rvm/gems/ruby-2.3.0@imap-backup/gems/imap-backup-1.1.0/bin/imap-backup:67:in `block in <top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.0@imap-backup/gems/imap-backup-1.1.0/lib/imap/backup/configuration/list.rb:21:in `block in each_connection'
	from /usr/local/rvm/gems/ruby-2.3.0@imap-backup/gems/imap-backup-1.1.0/lib/imap/backup/configuration/list.rb:19:in `each'
	from /usr/local/rvm/gems/ruby-2.3.0@imap-backup/gems/imap-backup-1.1.0/lib/imap/backup/configuration/list.rb:19:in `each_connection'
	from /usr/local/rvm/gems/ruby-2.3.0@imap-backup/gems/imap-backup-1.1.0/bin/imap-backup:66:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.0@imap-backup/bin/imap-backup:23:in `load'
	from /usr/local/rvm/gems/ruby-2.3.0@imap-backup/bin/imap-backup:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.3.0@imap-backup/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.3.0@imap-backup/bin/ruby_executable_hooks:15:in `<main>'
```

rvm, ruby, gem ... nothing changed.

Since then: not a single backup is working any more :(

Any ideas?

Please feel free to contact me if I can help in any way (additional testing, more data, ...).

Thank you very much in advance!

**Comment by joeyates** [comment]
Hello Anton,

Are you still getting the same error?
If so, please turn on logging and copy the output to a secret Gist and share that with me. (You may need to anonymize some stuff first).

**Comment by AntonTrapp** [comment]
Hi.

Thank you for your answer. Since I needed some backups in the last months I had to try other ways. So I am no longer using imap-backup.
