### ISSUE TITLE
`next_token': undefined method `dump' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by deconya** [joeyates/imap-backup#49]
Hi

Im testing in my own server and I receive this error
/home/user/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/imap.rb:3334:in `next_token': undefined method `dump' for nil:NilClass (NoMethodError)
	from /home/user/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/imap.rb:3279:in `lookahead'
	from /home/user/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/imap.rb:2285:in `msg_att'
	from /home/user/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/imap.rb:2276:in `numeric_response'
	from /home/user/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/imap.rb:2218:in `response_untagged'
	from /home/user/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/imap.rb:2198:in `response'
	from /home/user/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/imap.rb:2124:in `parse'
	from /home/user/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/imap.rb:1219:in `get_response'
	from /home/user/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/imap.rb:1127:in `receive_responses'
	from /home/user/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/net/imap.rb:1109:in `block in initialize'

If I do a status it works, but I can't download messages.

**Comment by joeyates** [comment]
Hello.

Could you give me some more info about your setup?

**Comment by joeyates** [comment]
Closing due to inactivity. Please feel free to reopen and add a sanitized log of the problem.
