### ISSUE TITLE
`fetch': undefined method `force_encoding' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by fliespl** [joeyates/imap-backup#52]
```
$ imap-backup 
D, [2018-05-24T08:57:18.697463 #15708] DEBUG -- : Running backup of account: x
D, [2018-05-24T08:57:18.697544 #15708] DEBUG -- : Creating IMAP instance: x, options: {:port=>993, :ssl=>{:verify_mode=>0}}
D, [2018-05-24T08:57:18.876536 #15708] DEBUG -- : Logging in: x
D, [2018-05-24T08:57:19.037723 #15708] DEBUG -- : Login complete
D, [2018-05-24T08:57:19.154224 #15708] DEBUG -- : [App Development] running backup
D, [2018-05-24T08:57:19.374945 #15708] DEBUG -- : [App Development] 0 new messages
D, [2018-05-24T08:57:19.375129 #15708] DEBUG -- : [Archive] running backup
D, [2018-05-24T08:57:19.589601 #15708] DEBUG -- : [Archive] 0 new messages
D, [2018-05-24T08:57:19.589825 #15708] DEBUG -- : [Arlians Campaigns] running backup
D, [2018-05-24T08:57:19.816552 #15708] DEBUG -- : [Arlians Campaigns] 0 new messages
D, [2018-05-24T08:57:19.816765 #15708] DEBUG -- : [Arlians.com Notifications] running backup
D, [2018-05-24T08:57:20.040087 #15708] DEBUG -- : [Arlians.com Notifications] 0 new messages
D, [2018-05-24T08:57:20.040324 #15708] DEBUG -- : [Calendar] running backup
D, [2018-05-24T08:57:20.314506 #15708] DEBUG -- : [Calendar] 1985 new messages
D, [2018-05-24T08:57:20.549175 #15708] DEBUG -- : [Calendar] 9 - not available - skipped
D, [2018-05-24T08:57:20.772456 #15708] DEBUG -- : [Calendar] 16 - not available - skipped
D, [2018-05-24T08:57:20.992801 #15708] DEBUG -- : [Calendar] 24 - not available - skipped
D, [2018-05-24T08:57:21.221103 #15708] DEBUG -- : [Calendar] 25 - not available - skipped
D, [2018-05-24T08:57:21.456011 #15708] DEBUG -- : [Calendar] 30 - not available - skipped
D, [2018-05-24T08:57:21.676347 #15708] DEBUG -- : [Calendar] 33 - not available - skipped
D, [2018-05-24T08:57:21.901910 #15708] DEBUG -- : [Calendar] 39 - not available - skipped
D, [2018-05-24T08:57:22.124641 #15708] DEBUG -- : [Calendar] 42 - not available - skipped
D, [2018-05-24T08:57:22.350973 #15708] DEBUG -- : [Calendar] 54 - not available - skipped
D, [2018-05-24T08:57:22.576765 #15708] DEBUG -- : [Calendar] 55 - not available - skipped
D, [2018-05-24T08:57:22.799640 #15708] DEBUG -- : [Calendar] 56 - not available - skipped
D, [2018-05-24T08:57:23.022502 #15708] DEBUG -- : [Calendar] 57 - not available - skipped
D, [2018-05-24T08:57:23.249829 #15708] DEBUG -- : [Calendar] 63 - not available - skipped
D, [2018-05-24T08:57:23.470018 #15708] DEBUG -- : [Calendar] 72 - not available - skipped
D, [2018-05-24T08:57:23.689962 #15708] DEBUG -- : [Calendar] 74 - not available - skipped
D, [2018-05-24T08:57:23.914456 #15708] DEBUG -- : [Calendar] 80 - not available - skipped
D, [2018-05-24T08:57:24.157435 #15708] DEBUG -- : [Calendar] 83 - not available - skipped
D, [2018-05-24T08:57:24.379108 #15708] DEBUG -- : [Calendar] 86 - not available - skipped
D, [2018-05-24T08:57:24.602591 #15708] DEBUG -- : [Calendar] 87 - not available - skipped
D, [2018-05-24T08:57:24.836377 #15708] DEBUG -- : [Calendar] 97 - not available - skipped
D, [2018-05-24T08:57:25.057179 #15708] DEBUG -- : [Calendar] 98 - not available - skipped
D, [2018-05-24T08:57:25.279608 #15708] DEBUG -- : [Calendar] 99 - not available - skipped
D, [2018-05-24T08:57:25.505529 #15708] DEBUG -- : [Calendar] 100 - not available - skipped
D, [2018-05-24T08:57:25.735752 #15708] DEBUG -- : [Calendar] 132 - not available - skipped
D, [2018-05-24T08:57:25.955192 #15708] DEBUG -- : [Calendar] 133 - not available - skipped
D, [2018-05-24T08:57:26.175346 #15708] DEBUG -- : [Calendar] 134 - not available - skipped
D, [2018-05-24T08:57:26.398751 #15708] DEBUG -- : [Calendar] 143 - not available - skipped
D, [2018-05-24T08:57:26.629987 #15708] DEBUG -- : [Calendar] 150 - not available - skipped
D, [2018-05-24T08:57:26.850151 #15708] DEBUG -- : [Calendar] 161 - not available - skipped
D, [2018-05-24T08:57:27.071312 #15708] DEBUG -- : [Calendar] 164 - not available - skipped
D, [2018-05-24T08:57:27.307170 #15708] DEBUG -- : [Calendar] 170 - not available - skipped
D, [2018-05-24T08:57:27.526631 #15708] DEBUG -- : [Calendar] 171 - not available - skipped
D, [2018-05-24T08:57:27.801769 #15708] DEBUG -- : [Calendar] 182 - not available - skipped
D, [2018-05-24T08:57:28.029958 #15708] DEBUG -- : [Calendar] 187 - not available - skipped
D, [2018-05-24T08:57:28.256562 #15708] DEBUG -- : [Calendar] 188 - not available - skipped
D, [2018-05-24T08:57:28.480596 #15708] DEBUG -- : [Calendar] 202 - not available - skipped
D, [2018-05-24T08:57:28.719669 #15708] DEBUG -- : [Calendar] 203 - not available - skipped
D, [2018-05-24T08:57:28.942111 #15708] DEBUG -- : [Calendar] 211 - not available - skipped
D, [2018-05-24T08:57:29.173936 #15708] DEBUG -- : [Calendar] 221 - not available - skipped
D, [2018-05-24T08:57:29.397058 #15708] DEBUG -- : [Calendar] 223 - not available - skipped
D, [2018-05-24T08:57:29.624307 #15708] DEBUG -- : [Calendar] 230 - not available - skipped
D, [2018-05-24T08:57:29.845674 #15708] DEBUG -- : [Calendar] 232 - not available - skipped
D, [2018-05-24T08:57:30.073074 #15708] DEBUG -- : [Calendar] 247 - not available - skipped
D, [2018-05-24T08:57:30.296493 #15708] DEBUG -- : [Calendar] 257 - not available - skipped
D, [2018-05-24T08:57:30.523178 #15708] DEBUG -- : [Calendar] 267 - not available - skipped
D, [2018-05-24T08:57:30.754832 #15708] DEBUG -- : [Calendar] 272 - not available - skipped
D, [2018-05-24T08:57:30.995680 #15708] DEBUG -- : [Calendar] 275 - not available - skipped
D, [2018-05-24T08:57:31.222119 #15708] DEBUG -- : [Calendar] 293 - not available - skipped
D, [2018-05-24T08:57:31.441580 #15708] DEBUG -- : [Calendar] 297 - not available - skipped
D, [2018-05-24T08:57:31.661643 #15708] DEBUG -- : [Calendar] 298 - not available - skipped
D, [2018-05-24T08:57:31.880348 #15708] DEBUG -- : [Calendar] 299 - not available - skipped
D, [2018-05-24T08:57:32.114453 #15708] DEBUG -- : [Calendar] 312 - not available - skipped
D, [2018-05-24T08:57:32.336561 #15708] DEBUG -- : [Calendar] 313 - not available - skipped
D, [2018-05-24T08:57:32.557476 #15708] DEBUG -- : [Calendar] 314 - not available - skipped
D, [2018-05-24T08:57:32.784587 #15708] DEBUG -- : [Calendar] 332 - not available - skipped
D, [2018-05-24T08:57:33.008278 #15708] DEBUG -- : [Calendar] 334 - not available - skipped
D, [2018-05-24T08:57:33.230083 #15708] DEBUG -- : [Calendar] 337 - not available - skipped
D, [2018-05-24T08:57:33.450221 #15708] DEBUG -- : [Calendar] 340 - not available - skipped
D, [2018-05-24T08:57:33.668562 #15708] DEBUG -- : [Calendar] 347 - not available - skipped
D, [2018-05-24T08:57:33.893745 #15708] DEBUG -- : [Calendar] 368 - not available - skipped
D, [2018-05-24T08:57:34.112950 #15708] DEBUG -- : [Calendar] 379 - not available - skipped
D, [2018-05-24T08:57:34.331072 #15708] DEBUG -- : [Calendar] 383 - not available - skipped
D, [2018-05-24T08:57:34.558401 #15708] DEBUG -- : [Calendar] 386 - not available - skipped
D, [2018-05-24T08:57:34.779122 #15708] DEBUG -- : [Calendar] 388 - not available - skipped
D, [2018-05-24T08:57:35.005877 #15708] DEBUG -- : [Calendar] 409 - not available - skipped
D, [2018-05-24T08:57:35.222756 #15708] DEBUG -- : [Calendar] 418 - not available - skipped
D, [2018-05-24T08:57:35.443637 #15708] DEBUG -- : [Calendar] 419 - not available - skipped
D, [2018-05-24T08:57:35.670058 #15708] DEBUG -- : [Calendar] 425 - not available - skipped
D, [2018-05-24T08:57:35.887157 #15708] DEBUG -- : [Calendar] 426 - not available - skipped
D, [2018-05-24T08:57:36.108085 #15708] DEBUG -- : [Calendar] 427 - not available - skipped
D, [2018-05-24T08:57:36.326720 #15708] DEBUG -- : [Calendar] 428 - not available - skipped
D, [2018-05-24T08:57:36.554083 #15708] DEBUG -- : [Calendar] 444 - not available - skipped
D, [2018-05-24T08:57:36.773495 #15708] DEBUG -- : [Calendar] 451 - not available - skipped
D, [2018-05-24T08:57:37.000371 #15708] DEBUG -- : [Calendar] 452 - not available - skipped
D, [2018-05-24T08:57:37.230603 #15708] DEBUG -- : [Calendar] 467 - not available - skipped
D, [2018-05-24T08:57:37.451416 #15708] DEBUG -- : [Calendar] 469 - not available - skipped
D, [2018-05-24T08:57:37.671547 #15708] DEBUG -- : [Calendar] 481 - not available - skipped
D, [2018-05-24T08:57:37.899690 #15708] DEBUG -- : [Calendar] 483 - not available - skipped
D, [2018-05-24T08:57:38.120262 #15708] DEBUG -- : [Calendar] 486 - not available - skipped
D, [2018-05-24T08:57:38.350335 #15708] DEBUG -- : [Calendar] 500 - not available - skipped
D, [2018-05-24T08:57:38.569963 #15708] DEBUG -- : [Calendar] 515 - not available - skipped
D, [2018-05-24T08:57:38.802667 #15708] DEBUG -- : [Calendar] 516 - not available - skipped
D, [2018-05-24T08:57:39.023063 #15708] DEBUG -- : [Calendar] 518 - not available - skipped
D, [2018-05-24T08:57:39.244001 #15708] DEBUG -- : [Calendar] 524 - not available - skipped
D, [2018-05-24T08:57:39.471089 #15708] DEBUG -- : [Calendar] 530 - not available - skipped
D, [2018-05-24T08:57:39.697055 #15708] DEBUG -- : [Calendar] 542 - not available - skipped
D, [2018-05-24T08:57:39.916404 #15708] DEBUG -- : [Calendar] 546 - not available - skipped
D, [2018-05-24T08:57:40.150110 #15708] DEBUG -- : [Calendar] 561 - not available - skipped
D, [2018-05-24T08:57:40.371860 #15708] DEBUG -- : [Calendar] 563 - not available - skipped
D, [2018-05-24T08:57:40.590505 #15708] DEBUG -- : [Calendar] 565 - not available - skipped
D, [2018-05-24T08:57:40.821013 #15708] DEBUG -- : [Calendar] 575 - not available - skipped
D, [2018-05-24T08:57:41.040378 #15708] DEBUG -- : [Calendar] 576 - not available - skipped
D, [2018-05-24T08:57:41.263818 #15708] DEBUG -- : [Calendar] 578 - not available - skipped
D, [2018-05-24T08:57:41.483331 #15708] DEBUG -- : [Calendar] 579 - not available - skipped
D, [2018-05-24T08:57:41.705133 #15708] DEBUG -- : [Calendar] 586 - not available - skipped
D, [2018-05-24T08:57:41.923691 #15708] DEBUG -- : [Calendar] 593 - not available - skipped
D, [2018-05-24T08:57:42.152493 #15708] DEBUG -- : [Calendar] 599 - not available - skipped
D, [2018-05-24T08:57:42.370493 #15708] DEBUG -- : [Calendar] 601 - not available - skipped
D, [2018-05-24T08:57:42.594759 #15708] DEBUG -- : [Calendar] 620 - not available - skipped
D, [2018-05-24T08:57:42.815492 #15708] DEBUG -- : [Calendar] 621 - not available - skipped
D, [2018-05-24T08:57:43.034328 #15708] DEBUG -- : [Calendar] 623 - not available - skipped
D, [2018-05-24T08:57:43.254472 #15708] DEBUG -- : [Calendar] 624 - not available - skipped
D, [2018-05-24T08:57:43.477389 #15708] DEBUG -- : [Calendar] 634 - not available - skipped
D, [2018-05-24T08:57:43.708144 #15708] DEBUG -- : [Calendar] 643 - not available - skipped
D, [2018-05-24T08:57:43.929359 #15708] DEBUG -- : [Calendar] 645 - not available - skipped
D, [2018-05-24T08:57:44.177695 #15708] DEBUG -- : [Calendar] 666 - not available - skipped
/var/lib/gems/2.3.0/gems/imap-backup-1.2.2/lib/imap/backup/account/folder.rb:40:in `fetch': undefined method `force_encoding' for nil:NilClass (NoMethodError)
	from /var/lib/gems/2.3.0/gems/imap-backup-1.2.2/lib/imap/backup/downloader.rb:16:in `block in run'
	from /var/lib/gems/2.3.0/gems/imap-backup-1.2.2/lib/imap/backup/downloader.rb:15:in `each'
	from /var/lib/gems/2.3.0/gems/imap-backup-1.2.2/lib/imap/backup/downloader.rb:15:in `run'
	from /var/lib/gems/2.3.0/gems/imap-backup-1.2.2/lib/imap/backup/account/connection.rb:44:in `block in run_backup'
	from /var/lib/gems/2.3.0/gems/imap-backup-1.2.2/lib/imap/backup/account/connection.rb:69:in `block in each_folder'
	from /var/lib/gems/2.3.0/gems/imap-backup-1.2.2/lib/imap/backup/account/connection.rb:66:in `each'
	from /var/lib/gems/2.3.0/gems/imap-backup-1.2.2/lib/imap/backup/account/connection.rb:66:in `each_folder'
	from /var/lib/gems/2.3.0/gems/imap-backup-1.2.2/lib/imap/backup/account/connection.rb:42:in `run_backup'
	from /var/lib/gems/2.3.0/gems/imap-backup-1.2.2/bin/imap-backup:72:in `block in <top (required)>'
	from /var/lib/gems/2.3.0/gems/imap-backup-1.2.2/lib/imap/backup/configuration/list.rb:21:in `block in each_connection'
	from /var/lib/gems/2.3.0/gems/imap-backup-1.2.2/lib/imap/backup/configuration/list.rb:19:in `each'
	from /var/lib/gems/2.3.0/gems/imap-backup-1.2.2/lib/imap/backup/configuration/list.rb:19:in `each_connection'
	from /var/lib/gems/2.3.0/gems/imap-backup-1.2.2/bin/imap-backup:71:in `<top (required)>'
	from /usr/local/bin/imap-backup:23:in `load'
	from /usr/local/bin/imap-backup:23:in `<main>'

```

**Comment by joeyates** [comment]
@fliespl I see you're accessing an email account which has calendar entries.

In order to resolve the problem, I'd like to understand a bit more about your setup.

1. Is the Calendar a Google Calendar?
2. How did you set up the connection between the calendar and your email account.

**Comment by joeyates** [comment]
OK, thanks for the info. Closing.
