### ISSUE TITLE
unable to backup message that does not contain (parseable?) date

### ISSUE THREAD

**Issue by doublerebel** [joeyates/imap-backup#61]
While backing up an email account, I received an error, probably due to the minutes and seconds in the dates being greater than 60:
```rb
Received: from [redacted] with Microsoft SMTP Server id A9JN3SY3; Mon,5 May 2014 08:97:99 GMT
Date: Mon,5 May 2014 08:86:06 GMT
```
Full error here:
```rb
D, [2018-12-18T17:18:16.245479 #7388] DEBUG -- : Logging in: email@domain.com/xxxxxxxxxxxxxxx
D, [2018-12-18T17:18:16.419229 #7388] DEBUG -- : Login complete
D, [2018-12-18T17:18:16.419472 #7388] DEBUG -- : [INBOX] running backup
D, [2018-12-18T17:18:17.077369 #7388] DEBUG -- : [INBOX] 2 new messages
D, [2018-12-18T17:18:17.477794 #7388] DEBUG -- : [INBOX] 411 - 10467 bytes
W, [2018-12-18T17:18:17.688178 #7388]  WARN -- : [INBOX] failed to save message 411:
Return-path: [redacted]
Envelope-to: email@domain.com
Delivery-date: Mon, 05 May 2014 09:04:18 -0400
Received: from [redacted]
	by lagertha.asmallorange.com with esmtp (Exim 4.82)
	(envelope-from [redacted])
	id 1WhIZ7-0001iX-Rd
	for [redacted]; Mon, 05 May 2014 09:04:18 -0400
Received: from [redacted] with Microsoft SMTP Server id A9JN3SY3; Mon,5 May 2014 08:97:99 GMT
Date: Mon,5 May 2014 08:86:06 GMT
From: [redacted]
Message-ID: <70706889916666130862516876092901175509@domain.com>
To: email@domain.com
Subject: FW: Balance Scheet
MIME-Version: 1.0
Content-Type: multipart/mixed;
  boundary="----=_Next_65421_4168646138.7677489752504"

------=_Next_65421_4168646138.7677489752504
Content-Type: text/plain; 
Content-Transfer-Encoding: 8bit

Please save the attached file to your hard drive before deleting this message. Thank you. 

------=_Next_65421_4168646138.7677489752504
Content-Type: application/zip; name="Sheet.zip"
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="Sheet.zip"

[base64 content removed]

------=_Next_65421_4168646138.7677489752504
. Mail::DateTimeElement can not parse ||: nil is invalid:
/var/lib/gems/2.3.0/gems/mail-2.7.1/lib/mail/parsers/date_time_parser.rb:668:in `parse'
/var/lib/gems/2.3.0/gems/mail-2.7.1/lib/mail/elements/date_time_element.rb:10:in `initialize'
/var/lib/gems/2.3.0/gems/mail-2.7.1/lib/mail/fields/common/common_date.rb:33:in `new'
/var/lib/gems/2.3.0/gems/mail-2.7.1/lib/mail/fields/common/common_date.rb:33:in `element'
/var/lib/gems/2.3.0/gems/mail-2.7.1/lib/mail/fields/common/common_date.rb:7:in `date_time'
/var/lib/gems/2.3.0/gems/mail-2.7.1/lib/mail/fields/common/common_date.rb:11:in `default'
/var/lib/gems/2.3.0/gems/mail-2.7.1/lib/mail/field.rb:239:in `method_missing'
/var/lib/gems/2.3.0/gems/mail-2.7.1/lib/mail/message.rb:1215:in `default'
/var/lib/gems/2.3.0/gems/mail-2.7.1/lib/mail/message.rb:621:in `date'
/var/lib/gems/2.3.0/gems/imap-backup-1.3.0/lib/email/mboxrd/message.rb:56:in `date'
/var/lib/gems/2.3.0/gems/imap-backup-1.3.0/lib/email/mboxrd/message.rb:52:in `asctime'
/var/lib/gems/2.3.0/gems/imap-backup-1.3.0/lib/email/mboxrd/message.rb:39:in `from'
/var/lib/gems/2.3.0/gems/imap-backup-1.3.0/lib/email/mboxrd/message.rb:15:in `to_s'
/var/lib/gems/2.3.0/gems/imap-backup-1.3.0/lib/imap/backup/serializer/mbox.rb:45:in `save'
/var/lib/gems/2.3.0/gems/imap-backup-1.3.0/lib/imap/backup/downloader.rb:20:in `block in run'
/var/lib/gems/2.3.0/gems/imap-backup-1.3.0/lib/imap/backup/downloader.rb:13:in `each'
/var/lib/gems/2.3.0/gems/imap-backup-1.3.0/lib/imap/backup/downloader.rb:13:in `run'
/var/lib/gems/2.3.0/gems/imap-backup-1.3.0/lib/imap/backup/account/connection.rb:44:in `block in run_backup'
/var/lib/gems/2.3.0/gems/imap-backup-1.3.0/lib/imap/backup/account/connection.rb:69:in `block in each_folder'
/var/lib/gems/2.3.0/gems/imap-backup-1.3.0/lib/imap/backup/account/connection.rb:66:in `each'
/var/lib/gems/2.3.0/gems/imap-backup-1.3.0/lib/imap/backup/account/connection.rb:66:in `each_folder'
/var/lib/gems/2.3.0/gems/imap-backup-1.3.0/lib/imap/backup/account/connection.rb:42:in `run_backup'
/var/lib/gems/2.3.0/gems/imap-backup-1.3.0/bin/imap-backup:70:in `block in <top (required)>'
/var/lib/gems/2.3.0/gems/imap-backup-1.3.0/lib/imap/backup/configuration/list.rb:19:in `block in each_connection'
/var/lib/gems/2.3.0/gems/imap-backup-1.3.0/lib/imap/backup/configuration/list.rb:17:in `each'
/var/lib/gems/2.3.0/gems/imap-backup-1.3.0/lib/imap/backup/configuration/list.rb:17:in `each_connection'
/var/lib/gems/2.3.0/gems/imap-backup-1.3.0/bin/imap-backup:69:in `<top (required)>'
/usr/local/bin/imap-backup:22:in `load'
/usr/local/bin/imap-backup:22:in `<main>'
```
I don't ruby much, so I fixed it by changing the default date in mail/lib/message.rb from 'nil' to a DateTime:
[`/var/lib/gems/2.3.0/gems/mail-2.7.1/lib/mail/message.rb:621`](https://github.com/mikel/mail/blob/master/lib/mail/message.rb#L613)
```rb
    def date( val = DateTime.new(1970,01,01) )
      default :date, val
    end
```
...but I'm sure there's a more proper way to set that default from imap-backup.

Otherwise everything worked flawlessly.  Thanks for your work!

**Comment by joeyates** [comment]
I've released 2.0.0rc2 with the fix.
