### ISSUE TITLE
Backup trying to operate on renamed folders

### ISSUE THREAD

**Issue by msbit** [joeyates/imap-backup#67]
If you:

* go through `imap-backup setup`, nominating specific folders
* rename the folders on the email service (eg Gmail)
* attempt to update the folder selection through `imap-backup setup`

the new named folder is available for selection (defaulting to not being selected) but the old named folder is not available for de-selection.

Then, running `imap-backup` will try and fetch from the (now non-existent) folder, resulting in an error like:

```
$ imap-backup
Traceback (most recent call last):
	20: from /Users/tom/.rbenv/versions/2.5.5/bin/imap-backup:23:in `<main>'
	19: from /Users/tom/.rbenv/versions/2.5.5/bin/imap-backup:23:in `load'
	18: from /Users/tom/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/imap-backup-2.0.0/bin/imap-backup:75:in `<top (required)>'
	17: from /Users/tom/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/imap-backup-2.0.0/lib/imap/backup/configuration/list.rb:17:in `each_connection'
	16: from /Users/tom/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/imap-backup-2.0.0/lib/imap/backup/configuration/list.rb:17:in `each'
	15: from /Users/tom/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/imap-backup-2.0.0/lib/imap/backup/configuration/list.rb:19:in `block in each_connection'
	14: from /Users/tom/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/imap-backup-2.0.0/bin/imap-backup:76:in `block in <top (required)>'
	13: from /Users/tom/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/imap-backup-2.0.0/lib/imap/backup/account/connection.rb:48:in `run_backup'
	12: from /Users/tom/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/imap-backup-2.0.0/lib/imap/backup/account/connection.rb:104:in `each_folder'
	11: from /Users/tom/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/imap-backup-2.0.0/lib/imap/backup/account/connection.rb:104:in `each'
	10: from /Users/tom/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/imap-backup-2.0.0/lib/imap/backup/account/connection.rb:107:in `block in each_folder'
	 9: from /Users/tom/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/imap-backup-2.0.0/lib/imap/backup/account/connection.rb:50:in `block in run_backup'
	 8: from /Users/tom/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/imap-backup-2.0.0/lib/imap/backup/account/folder.rb:42:in `uid_validity'
	 7: from /Users/tom/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/imap-backup-2.0.0/lib/imap/backup/account/folder.rb:78:in `examine'
	 6: from /Users/tom/.rbenv/versions/2.5.5/lib/ruby/2.5.0/net/imap.rb:470:in `examine'
	 5: from /Users/tom/.rbenv/versions/2.5.5/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	 4: from /Users/tom/.rbenv/versions/2.5.5/lib/ruby/2.5.0/net/imap.rb:472:in `block in examine'
	 3: from /Users/tom/.rbenv/versions/2.5.5/lib/ruby/2.5.0/net/imap.rb:1253:in `send_command'
	 2: from /Users/tom/.rbenv/versions/2.5.5/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
	 1: from /Users/tom/.rbenv/versions/2.5.5/lib/ruby/2.5.0/net/imap.rb:1271:in `block in send_command'
/Users/tom/.rbenv/versions/2.5.5/lib/ruby/2.5.0/net/imap.rb:1217:in `get_tagged_response':  Unknown Mailbox: Personal/2 (now in authenticated state) (Failure) (Net::IMAP::NoResponseError)
```

You can go into `~/.imap-backup/config.json` and remove the old folders manually from the `folders` JSON key, and then it operates normally.

A solution to this would be for subsequent folder specifications (via `imap-backup setup`) to remove non-existent folders from the current list of selected folders, though I'm not sure what impact this would have on previously fetched `.mbox` files.

**Comment by joeyates** [comment]
@msbit Thanks for the bug report.

I've released version 2.1.0 to address this issue.

Missing folders are now skipped during download, and are removed from the list of folders during setup.
