### ISSUE TITLE
Unable to get folder list for account

### ISSUE THREAD

**Issue by jaccorens** [joeyates/imap-backup#76]
I have an issue using map-backup on just one Apple iCloud account mailbox. The other configured account syncs just fine. I have no clue what can be wrong, mail can be read fine though my mailclient.

```
imap-backup --version
2.2.0

D, [2019-10-14T16:01:27.184074 #16728] DEBUG -- : Creating IMAP instance: imap.mail.me.com, options: {:port=>993, :ssl=>{:ssl_version=>:TLSv1_2}}
D, [2019-10-14T16:01:28.041037 #16728] DEBUG -- : Logging in: someusername@mac.com/xxxxxxxxxxxxxxxxxxx
D, [2019-10-14T16:01:28.425388 #16728] DEBUG -- : Login complete
W, [2019-10-14T16:01:29.240041 #16728]  WARN -- : Unable to get folder list for account someusername@mac.com
Unable to list account folders
```

Any advice on what to do for debugging?

**Comment by joeyates** [comment]
If the IMAP server is standards compliant, imap-backup should able to get the folder listing.

It would be good to know if anyone else with Apple email accounts is experiencing this problem.

**Comment by robrecord** [comment]
I am experiencing this issue, with a GoDaddy email account.

**Comment by joeyates** [comment]
@robrecord Thanks for the info.

**Comment by jaccorens** [comment]
I have this issue on just one iCloud account, a second configured iCloud account syncs just fine. Although the folder list does not seem to work, I get the output below after running a full backup with this problem account;

```
D, [2019-10-23T04:31:59.138591 #19362] DEBUG -- : Creating IMAP instance: imap.mail.me.com, options: {:port=>993, :ssl=>{:ssl_version=>:TLSv1_2}}
D, [2019-10-23T04:32:00.190401 #19362] DEBUG -- : Logging in: someusername@mac.com/xxxxxxxxxxxxxxxxxxx
D, [2019-10-23T04:32:00.576111 #19362] DEBUG -- : Login complete
D, [2019-10-23T04:32:01.122875 #19362] DEBUG -- : [INBOX] running backup
D, [2019-10-23T04:32:04.745267 #19362] DEBUG -- : [INBOX] 47 new messages
D, [2019-10-23T04:32:05.952609 #19362] DEBUG -- : [INBOX] uid: 80716 (1/47) - not available - skipped
D, [2019-10-23T04:32:06.993918 #19362] DEBUG -- : [INBOX] uid: 80872 (2/47) - not available - skipped
...
D, [2019-10-23T04:32:49.461218 #19362] DEBUG -- : [INBOX] uid: 81098 (46/47) - not available - skipped
D, [2019-10-23T04:32:50.693155 #19362] DEBUG -- : [INBOX] uid: 81099 (47/47) - not available - skipped
```

I think the issue resides on the IMAP server side, but I'm not sure how to debug further from here.

**Comment by jaccorens** [comment]
And for reference, the output from the other configured iCloud account;

```
D, [2019-10-23T04:32:50.694836 #19362] DEBUG -- : Running backup of account: theotheraccount@mac.com
D, [2019-10-23T04:32:50.695190 #19362] DEBUG -- : Creating IMAP instance: imap.mail.me.com, options: {:port=>993, :ssl=>{:ssl_version=>:TLSv1_2}}
D, [2019-10-23T04:32:51.580084 #19362] DEBUG -- : Logging in: theotheraccount@mac.com/xxxxxxxxxxxxxxxxxxx
D, [2019-10-23T04:32:52.290329 #19362] DEBUG -- : Login complete
D, [2019-10-23T04:32:53.439493 #19362] DEBUG -- : [INBOX] running backup
D, [2019-10-23T04:32:54.661602 #19362] DEBUG -- : [INBOX] 21 new messages
D, [2019-10-23T04:32:55.759370 #19362] DEBUG -- : [INBOX] uid: 56613 (1/21) - 83875 bytes
D, [2019-10-23T04:32:56.953699 #19362] DEBUG -- : [INBOX] uid: 56614 (2/21) - 82947 bytes
...
D, [2019-10-23T04:33:16.642166 #19362] DEBUG -- : [INBOX] uid: 56719 (20/21) - 75765 bytes
D, [2019-10-23T04:33:17.648848 #19362] DEBUG -- : [INBOX] uid: 56723 (21/21) - 72404 bytes
```

**Comment by joeyates** [comment]
@jaccorens Thanks for the further info.

Is there any difference (account age, permissions or folder layout) between the problematic and non problematic iCloud accounts?

**Comment by joeyates** [comment]
Closing due to inactivity.

**Comment by mignz** [comment]
Has anyone found a fix for this? I'm using a me.com account.

```
D, [2021-02-26T20:20:13.788422 #89] DEBUG -- : Creating IMAP instance: imap.mail.me.com, options: {:port=>993, :ssl=>{:verify_mode=>1}}
D, [2021-02-26T20:20:14.198652 #89] DEBUG -- : Logging in: m*****@me.com/xxxxxxxxxxxxxxxxxxx
D, [2021-02-26T20:20:14.723873 #89] DEBUG -- : Login complete
W, [2021-02-26T20:20:15.483064 #89]  WARN -- : Unable to get folder list for account m*****@me.com
W, [2021-02-26T20:20:15.483134 #89]  WARN -- : Unable to get folder list
```

**Comment by joeyates** [comment]
Hi @mignz 

It looks like there is a specific problem with iCloud IMAP. I've reopened this issue in the hope of finding more examples.

**Comment by creatureface** [comment]
Here is another trace from a GoDaddy account.   

D, [2021-07-09T20:31:59.197369 #89531] DEBUG -- : Creating IMAP instance: imap.secureserver.net, options: {:port=>993, :ssl=>{:ssl_version=>:TLSv1_2}}
D, [2021-07-09T20:31:59.399733 #89531] DEBUG -- : Logging in: name@redacted.com/xxxxxxxx
D, [2021-07-09T20:31:59.812077 #89531] DEBUG -- : Login complete
I, [2021-07-09T20:32:00.011932 #89531]  INFO -- : Unable to get folder list for account name@redacted.com
Traceback (most recent call last):
	26: from /usr/local/bin/imap-backup:23:in `<main>'
	25: from /usr/local/bin/imap-backup:23:in `load'
	24: from /Library/Ruby/Gems/2.6.0/gems/imap-backup-3.3.1/bin/imap-backup:74:in `<top (required)>'
	23: from /Library/Ruby/Gems/2.6.0/gems/imap-backup-3.3.1/lib/imap/backup/configuration/setup.rb:14:in `run'
	22: from /Library/Ruby/Gems/2.6.0/gems/imap-backup-3.3.1/lib/imap/backup/configuration/setup.rb:14:in `catch'
	21: from /Library/Ruby/Gems/2.6.0/gems/imap-backup-3.3.1/lib/imap/backup/configuration/setup.rb:15:in `block in run'
	20: from /Library/Ruby/Gems/2.6.0/gems/imap-backup-3.3.1/lib/imap/backup/configuration/setup.rb:15:in `loop'
	19: from /Library/Ruby/Gems/2.6.0/gems/imap-backup-3.3.1/lib/imap/backup/configuration/setup.rb:17:in `block (2 levels) in run'
	18: from /Library/Ruby/Gems/2.6.0/gems/imap-backup-3.3.1/lib/imap/backup/configuration/setup.rb:25:in `show_menu'
	17: from /Library/Ruby/Gems/2.6.0/gems/highline-2.0.3/lib/highline.rb:277:in `choose'
	16: from /Library/Ruby/Gems/2.6.0/gems/highline-2.0.3/lib/highline/menu.rb:415:in `select'
	15: from /Library/Ruby/Gems/2.6.0/gems/highline-2.0.3/lib/highline/menu.rb:449:in `value_for_selected_item'
	14: from /Library/Ruby/Gems/2.6.0/gems/imap-backup-3.3.1/lib/imap/backup/configuration/setup.rb:47:in `block (2 levels) in account_items'
	13: from /Library/Ruby/Gems/2.6.0/gems/imap-backup-3.3.1/lib/imap/backup/configuration/setup.rb:92:in `edit_account'
	12: from /Library/Ruby/Gems/2.6.0/gems/imap-backup-3.3.1/lib/imap/backup/configuration/account.rb:10:in `run'
	11: from /Library/Ruby/Gems/2.6.0/gems/imap-backup-3.3.1/lib/imap/backup/configuration/account.rb:10:in `catch'
	10: from /Library/Ruby/Gems/2.6.0/gems/imap-backup-3.3.1/lib/imap/backup/configuration/account.rb:11:in `block in run'
	 9: from /Library/Ruby/Gems/2.6.0/gems/imap-backup-3.3.1/lib/imap/backup/configuration/account.rb:11:in `loop'
	 8: from /Library/Ruby/Gems/2.6.0/gems/imap-backup-3.3.1/lib/imap/backup/configuration/account.rb:13:in `block (2 levels) in run'
	 7: from /Library/Ruby/Gems/2.6.0/gems/imap-backup-3.3.1/lib/imap/backup/configuration/account.rb:21:in `create_menu'
	 6: from /Library/Ruby/Gems/2.6.0/gems/highline-2.0.3/lib/highline.rb:277:in `choose'
	 5: from /Library/Ruby/Gems/2.6.0/gems/highline-2.0.3/lib/highline/menu.rb:415:in `select'
	 4: from /Library/Ruby/Gems/2.6.0/gems/highline-2.0.3/lib/highline/menu.rb:449:in `value_for_selected_item'
	 3: from /Library/Ruby/Gems/2.6.0/gems/imap-backup-3.3.1/lib/imap/backup/configuration/account.rb:120:in `block in choose_folders'
	 2: from /Library/Ruby/Gems/2.6.0/gems/imap-backup-3.3.1/lib/imap/backup/configuration/folder_chooser.rb:18:in `run'
	 1: from /Library/Ruby/Gems/2.6.0/gems/imap-backup-3.3.1/lib/imap/backup/configuration/folder_chooser.rb:104:in `imap_folders'
/Library/Ruby/Gems/2.6.0/gems/imap-backup-3.3.1/lib/imap/backup/account/connection.rb:42:in `folders': Unable to get folder list for account name@redacted.com (RuntimeError)

**Comment by joeyates** [comment]
In debug mode, imap-backup now outputs all data exchanged with the IMAP server (version >= 3.4.1).

If anyone who is having this error could paste a **redacted** version of the log where the error happens, it may help track down the problem.

**Comment by jdhorne** [comment]
I've attached a redacted log.

[imap-backup-log.txt](https://github.com/joeyates/imap-backup/files/7669180/imap-backup-log.txt)

**Comment by joeyates** [comment]
The iCloud IMAP server responds differently (I believe what it does is non-standard). I've added a workaround, so that @icloud.com, @mac.com and @me.com accounts get treated specially.

I've released this as version 4.0.3.

**Comment by philippgerard** [comment]
Is there a way to configure this special behavior also for other domains? I am using a custom domain with iCloud but experience the same problem.

**Comment by marcschumacher** [comment]
Same here

**Comment by marcschumacher** [comment]
@philippgerard There is a solution I had for this: aside your custom domain e-mail addresses there is also a primary email address with one of the domains (@icloud.com in my case for example). Replace the custom domain e-mail with this one and it should work. I found the email address on my iPad navigating to Settings - <iCloud settings with your name, usually on top> - Addresses. Here you can find your particular address that you should use, hope it helps.
