### ISSUE TITLE
imap.rb:1422:in block in search_internal': undefined method []' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by KevinBongart** [joeyates/imap-backup#77]
I'm running into the same error as @tomathyg in https://github.com/joeyates/imap-backup/issues/65, also a non-Gmail account.

```
[...]
D, [2019-10-25T06:06:16.471725 #50815] DEBUG -- : [INBOX.Sent] running backup
D, [2019-10-25T06:06:18.594469 #50815] DEBUG -- : [INBOX.Sent] 0 new messages
D, [2019-10-25T06:06:18.989877 #50815] DEBUG -- : [INBOX.Spam] running backup
D, [2019-10-25T06:06:20.163413 #50815] DEBUG -- : [INBOX.Spam] 0 new messages
D, [2019-10-25T06:06:20.562224 #50815] DEBUG -- : [INBOX.Trash] running backup
D, [2019-10-25T06:06:21.749464 #50815] DEBUG -- : [INBOX.Trash] 0 new messages
D, [2019-10-25T06:06:22.198938 #50815] DEBUG -- : [INBOX.WatchThis] running backup
D, [2019-10-25T06:06:25.207510 #50815] DEBUG -- : [INBOX.WatchThis] 0 new messages
/Users/kevin/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/imap.rb:1422:in `block in search_internal': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/kevin/.rbenv/versions/2.6.3/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
	from /Users/kevin/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/imap.rb:1416:in `search_internal'
	from /Users/kevin/.rbenv/versions/2.6.3/lib/ruby/2.6.0/net/imap.rb:779:in `uid_search'
	from /Users/kevin/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/imap-backup-2.2.0/lib/imap/backup/account/folder.rb:52:in `uids'
	from /Users/kevin/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/imap-backup-2.2.0/lib/imap/backup/downloader.rb:12:in `run'
	from /Users/kevin/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/imap-backup-2.2.0/lib/imap/backup/account/connection.rb:54:in `block in run_backup'
	from /Users/kevin/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/imap-backup-2.2.0/lib/imap/backup/account/connection.rb:93:in `block in each_folder'
	from /Users/kevin/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/imap-backup-2.2.0/lib/imap/backup/account/connection.rb:90:in `each'
	from /Users/kevin/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/imap-backup-2.2.0/lib/imap/backup/account/connection.rb:90:in `each_folder'
	from /Users/kevin/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/imap-backup-2.2.0/lib/imap/backup/account/connection.rb:49:in `run_backup'
	from /Users/kevin/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/imap-backup-2.2.0/lib/imap/backup/configuration/list.rb:20:in `block in each_connection'
	from /Users/kevin/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/imap-backup-2.2.0/lib/imap/backup/configuration/list.rb:18:in `each'
	from /Users/kevin/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/imap-backup-2.2.0/lib/imap/backup/configuration/list.rb:18:in `each_connection'
	from /Users/kevin/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/imap-backup-2.2.0/bin/imap-backup:73:in `<top (required)>'
	from /Users/kevin/.rbenv/versions/2.6.3/bin/imap-backup:23:in `load'
	from /Users/kevin/.rbenv/versions/2.6.3/bin/imap-backup:23:in `<main>'
D, [2019-10-25T07:03:42.168109 #51537] DEBUG -- : Running backup of account: *****@fastmail.com
D, [2019-10-25T07:03:42.168496 #51537] DEBUG -- : Creating IMAP instance: mail.messagingengine.com, options: {:port=>993, :ssl=>{:ssl_version=>:TLSv1_2}}
D, [2019-10-25T07:03:42.797836 #51537] DEBUG -- : Logging in: *****@fastmail.com/xxxxxxxxxxxxxxxx
D, [2019-10-25T07:03:43.047046 #51537] DEBUG -- : Login complete
D, [2019-10-25T07:03:46.615889 #51537] DEBUG -- : [INBOX] running backup
D, [2019-10-25T08:05:25.449144 #52496] DEBUG -- : Running backup of account: *****@fastmail.com
D, [2019-10-25T08:05:25.449201 #52496] DEBUG -- : Creating IMAP instance: mail.messagingengine.com, options: {:port=>993, :ssl=>{:ssl_version=>:TLSv1_2}}
D, [2019-10-25T08:05:32.414279 #52496] DEBUG -- : Logging in: *****@fastmail.com/xxxxxxxxxxxxxxxx
D, [2019-10-25T08:05:34.891387 #52496] DEBUG -- : Login complete
D, [2019-10-25T08:05:54.880581 #52496] DEBUG -- : [INBOX] running backup
D, [2019-10-25T08:05:57.422518 #52496] DEBUG -- : [INBOX] 0 new messages
[...]
```

Note that `imap-backup` runs in an hourly cronjob, most of the time completing successfully, sometimes finding new mail to back up and sometimes nothing new. This is not blocking my workflow as the backup eventually completes.

In the trace above, `WatchThis` is a folder I created manually many years ago and hasn't gotten any new messages moved in for quite some time. It is the last IMAP folder when these are sorted alphabetically, so the error could have happened at the beginning of the 7am backup (which, while it logged some lines right after, doesn't seem to have completed).

The last `imap-backup` line of code involved is this one: https://github.com/joeyates/imap-backup/blob/d66610625d66a611355211610f7b0ef3d67cddd8/lib/imap/backup/account/folder.rb#L52

Happy to provide more context if needed, or to use a branch with more logging. Again, not critical for me.

Thanks for this very useful gem!

**Comment by joeyates** [comment]
Hi @KevinBongart thanks for the bug report.

I've released v2.2.1 which handles the error and skips the folder.
I'm not clear why this is happening, but the error gets logged so you should see which folder are causing this - that way we may be able to understand the root cause.

@tomathyg - please try this out.

**Comment by KevinBongart** [comment]
Thanks for the quick fix! I saw the same error again on a different folder last night before I updated the gem. I'll post the trace of what causes it if I see it again

**Comment by KevinBongart** [comment]
Got this log a few hours ago:

```
D, [2019-10-29T04:00:53.510944 #3705] DEBUG -- : [INBOX.Drafts] running backup
W, [2019-10-29T04:05:35.527269 #3705]  WARN -- : Folder 'INBOX.Drafts' caused NoMethodError
probably
`undefined method `[]' for nil:NilClass (NoMethodError)`
in `search_internal` in stdlib net/imap.rb.
This is caused by `@responses["SEARCH"] being unset/undefined

D, [2019-10-29T04:05:35.527304 #3705] DEBUG -- : [INBOX.Drafts] 0 new messages
```

The good news is your fix did catch the error and let the backup complete, the bad news is… that draft folder is empty and has been empty for several days, yet the hourly backup job failed at 4am but worked at 3am and at 5am.

Anything I can do to investigate this some more?

**Comment by joeyates** [comment]
@KevinBongart Maybe this happens with empty folders on Fastmail. If that is the case, then we may not actually be missing anything with this fix.

It'd be interesting to hear if this happens to other Fastmail users.
