### ISSUE TITLE
Sporadic EOFError in `get_tagged_response' on running imap-backup

### ISSUE THREAD

**Issue by bentolor** [joeyates/imap-backup#81]
On running `imap-backup` it aborted quickly and spilled this stacktracke.  A subsequent run worked without errors.

```
~  $ imap-backup
Traceback (most recent call last):
	13: from /usr/local/bin/imap-backup:23:in `<main>'
	12: from /usr/local/bin/imap-backup:23:in `load'
	11: from /var/lib/gems/2.7.0/gems/imap-backup-2.2.1/bin/imap-backup:73:in `<top (required)>'
	10: from /var/lib/gems/2.7.0/gems/imap-backup-2.2.1/lib/imap/backup/configuration/list.rb:18:in `each_connection'
	 9: from /var/lib/gems/2.7.0/gems/imap-backup-2.2.1/lib/imap/backup/configuration/list.rb:18:in `each'
	 8: from /var/lib/gems/2.7.0/gems/imap-backup-2.2.1/lib/imap/backup/configuration/list.rb:20:in `block in each_connection'
	 7: from /var/lib/gems/2.7.0/gems/imap-backup-2.2.1/lib/imap/backup/account/connection.rb:48:in `run_backup'
	 6: from /var/lib/gems/2.7.0/gems/imap-backup-2.2.1/lib/imap/backup/account/connection.rb:82:in `imap'
	 5: from /usr/lib/ruby/2.7.0/net/imap.rb:441:in `login'
	 4: from /usr/lib/ruby/2.7.0/net/imap.rb:1255:in `send_command'
	 3: from /usr/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
	 2: from /usr/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
	 1: from /usr/lib/ruby/2.7.0/net/imap.rb:1273:in `block in send_command'
/usr/lib/ruby/2.7.0/net/imap.rb:1213:in `get_tagged_response': end of file reached (EOFError)
```

**Comment by joeyates** [comment]
Thanks @bentolor ,

Looks like a network glitch. Probably need to have a retry mechanism around that call. I'll leave this open until we get a fix.

**Comment by joeyates** [comment]
I have implemented a retry mechanism (in certain specific cases). It's released as version3.2.0.
