### ISSUE TITLE
Can't list folders; undefined method `name' for "INBOX":String (NoMethodError)

### ISSUE THREAD

**Issue by reinouts** [joeyates/imap-backup#89]
Hi,

With the latest imap-backup I'm running into this issue. Is there anything I'm doing wrong? 

```
[ronwil@m5530-res ~]$ imap-backup folders
<redacted>@vanschouwen.info
Traceback (most recent call last):
	8: from /home/ronwil/bin/imap-backup:23:in `<main>'
	7: from /home/ronwil/bin/imap-backup:23:in `load'
	6: from /home/ronwil/.gem/ruby/gems/imap-backup-3.2.0/bin/imap-backup:78:in `<top (required)>'
	5: from /home/ronwil/.gem/ruby/gems/imap-backup-3.2.0/lib/imap/backup/configuration/list.rb:18:in `each_connection'
	4: from /home/ronwil/.gem/ruby/gems/imap-backup-3.2.0/lib/imap/backup/configuration/list.rb:18:in `each'
	3: from /home/ronwil/.gem/ruby/gems/imap-backup-3.2.0/lib/imap/backup/configuration/list.rb:20:in `block in each_connection'
	2: from /home/ronwil/.gem/ruby/gems/imap-backup-3.2.0/bin/imap-backup:85:in `block in <top (required)>'
	1: from /home/ronwil/.gem/ruby/gems/imap-backup-3.2.0/bin/imap-backup:85:in `each'
/home/ronwil/.gem/ruby/gems/imap-backup-3.2.0/bin/imap-backup:85:in `block (2 levels) in <top (required)>': undefined method `name' for "INBOX":String (NoMethodError)

[ronwil@m5530-res ~]$ ruby --version
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
```

**Comment by joeyates** [comment]
@reinouts Thanks for the bug report. I've fixed this in v3.2.1.
