### ISSUE TITLE
end of file reached (EOFError)

### ISSUE THREAD

**Issue by DunklerPhoenix** [joeyates/imap-backup#95]
Heho.
Sorry to throw the next error message to you. 
This one I had multiple times now. If I restart the command it works as normal, but sometimes it stops with "EOFError".

```
D, [2021-02-22T13:46:46.425500 #25639] DEBUG -- : [[Gmail]/Alle Nachrichten] uid: 294513 (6906/151256) - 126043 bytes
D, [2021-02-22T13:46:48.325435 #25639] DEBUG -- : [[Gmail]/Alle Nachrichten] uid: 294514 (6907/151256) - 24190 bytes
Traceback (most recent call last):
        23: from /usr/local/bin/imap-backup:23:in `<main>'
        22: from /usr/local/bin/imap-backup:23:in `load'
        21: from /var/lib/gems/2.5.0/gems/imap-backup-3.3.1/bin/imap-backup:76:in `<top (required)>'
        20: from /var/lib/gems/2.5.0/gems/imap-backup-3.3.1/lib/imap/backup/configuration/list.rb:18:in `each_connection'
        19: from /var/lib/gems/2.5.0/gems/imap-backup-3.3.1/lib/imap/backup/configuration/list.rb:18:in `each'
        18: from /var/lib/gems/2.5.0/gems/imap-backup-3.3.1/lib/imap/backup/configuration/list.rb:20:in `block in each_connection'
        17: from /var/lib/gems/2.5.0/gems/imap-backup-3.3.1/lib/imap/backup/account/connection.rb:62:in `run_backup'
        16: from /var/lib/gems/2.5.0/gems/imap-backup-3.3.1/lib/imap/backup/account/connection.rb:125:in `each_folder'
        15: from /var/lib/gems/2.5.0/gems/imap-backup-3.3.1/lib/imap/backup/account/connection.rb:125:in `each'
        14: from /var/lib/gems/2.5.0/gems/imap-backup-3.3.1/lib/imap/backup/account/connection.rb:128:in `block in each_folder'
        13: from /var/lib/gems/2.5.0/gems/imap-backup-3.3.1/lib/imap/backup/account/connection.rb:68:in `block in run_backup'
        12: from /var/lib/gems/2.5.0/gems/imap-backup-3.3.1/lib/imap/backup/downloader.rb:15:in `run'
        11: from /var/lib/gems/2.5.0/gems/imap-backup-3.3.1/lib/imap/backup/downloader.rb:15:in `with_index'
        10: from /var/lib/gems/2.5.0/gems/imap-backup-3.3.1/lib/imap/backup/downloader.rb:15:in `each'
         9: from /var/lib/gems/2.5.0/gems/imap-backup-3.3.1/lib/imap/backup/downloader.rb:16:in `block in run'
         8: from /var/lib/gems/2.5.0/gems/imap-backup-3.3.1/lib/imap/backup/account/folder.rb:72:in `fetch'
         7: from /var/lib/gems/2.5.0/gems/imap-backup-3.3.1/lib/imap/backup/account/folder.rb:98:in `examine'
         6: from /usr/lib/ruby/2.5.0/net/imap.rb:470:in `examine'
         5: from /usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
         4: from /usr/lib/ruby/2.5.0/net/imap.rb:472:in `block in examine'
         3: from /usr/lib/ruby/2.5.0/net/imap.rb:1253:in `send_command'
         2: from /usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
         1: from /usr/lib/ruby/2.5.0/net/imap.rb:1271:in `block in send_command'
/usr/lib/ruby/2.5.0/net/imap.rb:1211:in `get_tagged_response': end of file reached (EOFError)

```

Version: 3.3.1
Related Issues:
- https://github.com/joeyates/imap-backup/issues/81
- https://github.com/joeyates/imap-backup/issues/85

**Comment by DunklerPhoenix** [comment]
I really don't know xD

I'll test it the next days.

**Comment by DunklerPhoenix** [comment]
I didn't see this error again. Seems to be ok. If now I scream here a litte bit :P
