### ISSUE TITLE
SSL Problems connecting to Protonmail Bridge IMAP

### ISSUE THREAD

**Issue by processor286** [joeyates/imap-backup#97]
Trying to use imap-backup to pull messages out of protonmail using their bridge.

When I configured the bridge, I tested it with kmail, and kmail can use the bridge imap server, though it gave a warning and I accepted the bridge's self signed ssl certificate, then it worked.

The bridge provides an imap port on localhost port 1143 , so I configured imap-backup thus:

```
  "accounts": [
    {
      "username": "username",
      "password": "password",
      "server": "127.0.0.1",

...

      "connection_options": {
        "ssl": {"verify_mode": 0},
        "port": 1143
      }

...

  "debug": false
}

```

This results in the following SSL error:

```
Traceback (most recent call last):
        14: from /usr/bin/imap-backup.ruby2.7:23:in `<main>'
        13: from /usr/bin/imap-backup.ruby2.7:23:in `load'
        12: from /usr/lib64/ruby/gems/2.7.0/gems/imap-backup-3.3.1/bin/imap-backup:76:in `<top (required)>'
        11: from /usr/lib64/ruby/gems/2.7.0/gems/imap-backup-3.3.1/lib/imap/backup/configuration/list.rb:18:in `each_connection'
        10: from /usr/lib64/ruby/gems/2.7.0/gems/imap-backup-3.3.1/lib/imap/backup/configuration/list.rb:18:in `each'
         9: from /usr/lib64/ruby/gems/2.7.0/gems/imap-backup-3.3.1/lib/imap/backup/configuration/list.rb:20:in `block in each_connection'
         8: from /usr/lib64/ruby/gems/2.7.0/gems/imap-backup-3.3.1/lib/imap/backup/account/connection.rb:61:in `run_backup'
         7: from /usr/lib64/ruby/gems/2.7.0/gems/imap-backup-3.3.1/lib/imap/backup/account/connection.rb:93:in `imap'
         6: from /usr/lib64/ruby/gems/2.7.0/gems/imap-backup-3.3.1/lib/retry_on_error.rb:4:in `retry_on_error'
         5: from /usr/lib64/ruby/gems/2.7.0/gems/imap-backup-3.3.1/lib/imap/backup/account/connection.rb:98:in `block in imap'
         4: from /usr/lib64/ruby/gems/2.7.0/gems/imap-backup-3.3.1/lib/imap/backup/account/connection.rb:98:in `new'
         3: from /usr/lib64/ruby/2.7.0/net/imap.rb:1093:in `initialize'
         2: from /usr/lib64/ruby/2.7.0/net/imap.rb:1535:in `start_tls_session'
         1: from /usr/lib64/ruby/2.7.0/net/protocol.rb:44:in `ssl_socket_connect'
time="Feb 26 21:47:55.876" level=error msg="cannot send response:  write tcp 127.0.0.1:1143->127.0.0.1:36288: write: connection reset by peer\n" pkg=server-imap
/usr/lib64/ruby/2.7.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: wrong version number (OpenSSL::SSL::SSLError)
time="Feb 26 21:47:55.877" level=error msg="cannot send response:  write tcp 127.0.0.1:1143->127.0.0.1:36288: write: connection reset by peer\n" pkg=server-imap
time="Feb 26 21:47:55.877" level=error msg="cannot send response:  write tcp 127.0.0.1:1143->127.0.0.1:36288: write: connection reset by peer\n" pkg=server-imap
time="Feb 26 21:47:55.877" level=error msg="cannot send response:  write tcp 127.0.0.1:1143->127.0.0.1:36288: write: connection reset by peer\n" pkg=server-imap
time="Feb 26 21:47:55.877" level=error msg="cannot send response:  write tcp 127.0.0.1:1143->127.0.0.1:36288: write: connection reset by peer\n" pkg=server-imap
time="Feb 26 21:47:55.877" level=error msg="cannot send response:  write tcp 127.0.0.1:1143->127.0.0.1:36288: write: connection reset by peer\n" pkg=server-imap
time="Feb 26 21:47:55.877" level=error msg="cannot send response:  write tcp 127.0.0.1:1143->127.0.0.1:36288: write: connection reset by peer\n" pkg=server-imap
```

Have I missed a configuration option somewhere? 

Environment details:

```
OpenSUSE Tumbleweed
ruby --version
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux-gnu]
```

**Comment by joeyates** [comment]
Hi @processor286 

I think the best thing is to work out which ciphers the bridge supports.

`imap-backup` uses this config by default:

```ruby
{port: 993, ssl: {ssl_version: :TLSv1_2}}
```

so, servers needs to support `TLSv1.2` for that to work out of the box.

Please run the following:

```sh
nmap --script ssl-enum-ciphers -Pn -p 1143 127.0.0.1
```

As an example, here's the output I get for GMail's server:

```sh
$ nmap --script ssl-enum-ciphers -Pn -p 993 imap.gmail.com
Host discovery disabled (-Pn). All addresses will be marked 'up' and scan times will be slower.
Starting Nmap 7.91 ( https://nmap.org ) at 2021-03-20 12:04 CET
Nmap scan report for imap.gmail.com (108.177.15.108)
Host is up (0.072s latency).
Other addresses for imap.gmail.com (not scanned): 108.177.15.109
rDNS record for 108.177.15.108: wr-in-f108.1e100.net

PORT    STATE SERVICE
993/tcp open  imaps
| ssl-enum-ciphers:
|   TLSv1.0:
|     ciphers:
|       TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (ecdh_x25519) - A
|       TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (ecdh_x25519) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C
|     compressors:
|       NULL
|     cipher preference: server
|     warnings:
|       64-bit block cipher 3DES vulnerable to SWEET32 attack
|   TLSv1.1:
|     ciphers:
|       TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (ecdh_x25519) - A
|       TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (ecdh_x25519) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C
|     compressors:
|       NULL
|     cipher preference: server
|     warnings:
|       64-bit block cipher 3DES vulnerable to SWEET32 attack
|   TLSv1.2:
|     ciphers:
|       TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (ecdh_x25519) - A
|       TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (ecdh_x25519) - A
|       TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (ecdh_x25519) - A
|       TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (ecdh_x25519) - A
|       TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (ecdh_x25519) - A
|       TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (ecdh_x25519) - A
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C
|       TLS_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_AES_128_GCM_SHA256 (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_GCM_SHA384 (rsa 2048) - A
|     compressors:
|       NULL
|     cipher preference: client
|     warnings:
|       64-bit block cipher 3DES vulnerable to SWEET32 attack
|_  least strength: C

Nmap done: 1 IP address (1 host up) scanned in 4.30 seconds
```

**Comment by johnjones4** [comment]
@processor286 wondering if you ever solved this as I am encountering the same issue.

**Comment by processor286** [comment]
Sorry no. I needed a robust IMAP solution so I off-boarded from Proton Mail and moved to another provider.

**Comment by johnjones4** [comment]
All good. Thanks!

**Comment by joeyates** [comment]
Closing.
